version: '3'
services:
  redis:
    container_name: beast_docker_redis
    image: redis
    ports:
      - "${REDIS_CONTAINER_PORT}"
    # Setting the server password on start.
    command: redis-server --requirepass ${REDIS_PASSWORD} --port "${REDIS_PORT}"
  hubful_redis:
    container_name: beast_docker_hubful_redis
    image: redis
    ports:
      - "${HUBFUL_REDIS_CONTAINER_PORT}"
    # Setting the server password on start.
    command: redis-server --requirepass ${HUBFUL_REDIS_PASSWORD} --port "${HUBFUL_REDIS_PORT}"
  db:
    container_name: beast_docker_db
    image: postgres:alpine
    ports:
      - "${DB_CONTAINER_PORT}"
    # Runs every shell script found in this directory by using volumes.
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ${DB_DATABASES}
  # web:
  #   image: beast-backend-server
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - "db"
  #   command: ["./scripts/wait-for-it.sh", "db:5432", "--", "node", "index.js"]
  #   environment:
  #     DB_HOST: db
  #     REDIS_HOST: redis
