version: '3'
services:
  atomly_redis:
    container_name: atomly_redis
    image: redis
    env_file:
      - .env
    ports:
      - "${REDIS_CONTAINER_PORT}"
    # Setting the server password on start.
    command: redis-server --requirepass ${REDIS_PASSWORD} --port "${REDIS_PORT}"
  atomly_redis_hubful:
    container_name: atomly_redis_hubful
    image: redis
    env_file:
      - .env
    ports:
      - "${REDIS_HUBFUL_CONTAINER_PORT}"
    # Setting the server password on start.
    command: redis-server --requirepass ${REDIS_HUBFUL_PASSWORD} --port "${REDIS_HUBFUL_PORT}"
  atomly_postgres_db:
    container_name: atomly_postgres_db
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - "${DB_CONTAINER_PORT}"
    # # Runs every shell script found in this directory by using volumes.
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_MULTIPLE_DATABASES: ${DB_DATABASES}
      # POSTGRES_DATABASE: test
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
